---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: socks-shop-ms
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: exam
