---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: exam
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/Innocent9712/microservices-demo.git
  # url: https://github.com/Innocent9712/test-flux.git

